name: Build with Bazel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true
      
      # Install libtinfo5 (ncurses compat lib required by Bazel toolchain)
      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install -y libtinfo5

      - name: Build Folly
        run: |
          bazel build @folly//...
